//
//  Number.h
//  harmonicCities
//
//  Created by Carlos Molinero on 19/09/2015.
//  Copyright (c) 2015 Carlos Molinero. All rights reserved.
//

#ifndef __harmonicCities__Number__
#define __harmonicCities__Number__

//struct Proxy{
//    
//    //TODO let's see how to do this correctly in the future
//        operator double() const { return 1.1; }
//        operator long() const { return 1.1; }
//        operator signed long long() const { return 1.1; }
//        operator int() const { return 2; }
//};

#include <stdio.h>
#include <vector>
#include <unordered_map>
class Number{
public:
    
    
    std::vector<double> minOtherDistances;//TODO. this is a problem generated by the heap that calls CompareFunction.cpp and that needs this vector, I have to fix this;... I dont use this vector for anything in this case.
    std::vector<long> numOtherChildren;//TODO same here;
    double heuristicDistanceToGoal;//TODO same here;
    static double getValue( Number* &a);
    static bool compare(Number* &a,Number* &b);
    static void setIndexInHeap(Number* &number,long index,long indexOfTheHeap);
    static long getIndexInHeap( Number* &number,long indexOfTheHeap);
    void operator =(double value);
    bool operator < ( const Number& s ) const;
    bool operator < ( const Number* s ) const;
    bool operator > ( const Number& s ) const;
    bool operator == ( const Number& s ) const;
    bool operator >= ( const Number& s ) const;
    bool operator <= ( const Number& s ) const;
    bool operator()(const Number *comp1, const Number *comp2) const ;
    bool operator()(const Number &comp1, const Number &comp2) const ;
    
//    Proxy getValue();
    
//    double getValue();
//    double setValue();
//    long getId();
//    long setId();
////    long value();
//    
//private:
//    double value_double;
//    long value_long;
    double value;
    long id;
    long qualifier;
//    std::unordered_map<long,long> indexInHeap;
    long indexInHeap;
    
    
};

#endif /* defined(__harmonicCities__Number__) */
